package fredver.ioutils;

import java.util.Arrays;
import java.util.regex.Pattern;

import fredver.errorhandling.CheckedIllegalArgumentException;

public class Message {
	THE CLASS MESSAGE TO REPRESENT A WHOLE MESSAGE IS NOT A GOOD WAY TO APPROACH SENDING DATA,
	BECAUSE IT IS NOT FEASIBLE TO LOAD A WHOLE 10 GIGABYTE FILE INTO RAM. IT HAS TO BE APPROACHED WITH A BUFFER.
	PLEASE, WHATEVER IMPLEMENTATION YOU DECIDE ON, DOCUMENT IT IN THE README FILE.
}