package fredver.clientserver;

public enum PermissionLevel {
	USER,
	ADMIN,
}

SECONDO ME NON SERVE UN ENUM PERMISSIONLEVEL, SECONDO ME BASTA UN BOOLEAN
DA QUALCHE PARTE CHE TENGA CONTO SE UN USER SIA USER O ADMIN.