name: Compile Installer Class

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      # Step 3: Compile the specific Main class
      - name: Compile Installer class
        run: javac -d . ServerTelefono/src/fredver/clientserver/Installer.java

      # Step 4: Package the compiled Main class into a JAR file
      - name: Create JAR file
        run: jar cfe installer.jar fredver.clientserver.Installer -C . fredver

      # Step 5: Configure git
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Force add and commit the JAR file to the root directory
      - name: Commit JAR file
        run: |
          git add -f installer.jar
          git commit -m "Add compiled installer.jar"

      # Step 7: Push changes
      - name: Push changes
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://${REPO_TOKEN}@github.com/${{ github.repository }}
          git push origin master
